apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
        - name: runner
          image: gcr.io/mechmania2017/runner:latest
          volumeMounts:
          - mountPath: /bots
            name: bots
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: mongo
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: rabbitmq
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: aws_secret_access_key
      volumes:
      - name: bots
        emptyDir: {}